#!/bin/bash
#SBATCH --job-name=surging
#SBATCH --time=10:0:0
# SBATCH --partition=lrgmem
# SBATCH --partition=shared
# SBATCH --partition=parallel
#SBATCH --partition=gpuk80
#SBATCH -N 1
# SBATCH --ntasks-per-node=28

# SBATCH –gres=gpu:24 
# number of tasks (processes) per node
# SBATCH --ntasks-per-node=2
# SBATCH --mem-per-cpu=4900
#SBATCH --mem=112640
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=all
#SBATCH --mail-user=yhuang98@jhu.edu
#SBATCH --output=out/job-%J.out

#SBATCH --array=0-3
# SBATCH --array=101-101
# SBATCH --array=99-99

#### load and unload modules you may need

ml anaconda
conda activate /home-net/home-4/yhuang98@jhu.edu/code/ABMpy/env

python -u sim_single_region_$SLURM_ARRAY_TASK_ID.py

echo "Finished with job $SLURM_JOBID"
#echo "Finished with job $SLURM_ARRAY_TASK_ID"

